export const LOADING_DUMMYUSERS = "LOADING DUMMYUSERS";
export const GET_DUMMYUSERS = "GET DUMMYUSERS";
export const DELETE_DUMMYUSER = "DELETE DUMMYUSER";
export const UPDATE_DUMMYUER = "UPDATE DUMMYUER";
export const CREATE_DUMMYUSER = "CREATE DUMMYUSER"


export const MODAL_OPEN = "MODAL OPEN";
export const MODAL_CLOSE = "MODAL CLOSE";
export const IS_OPEN_CONFIRM_MODAL = "IS OPEN CONFIRM MODAL"
export const IS_OPEN_MODAL = "IS OPEN MODAL"
export const MODAL_OPEN_CONFIRM = "MODAL OPEN CONFIRM"
export const MODAL_CLOSE_CONFIRM = "MODAL CLOSE CONFIRM"

export const USER_LOADING = "USER LOADING"
export const USER_LOADED = "USER LOADED"
export const LOGIN_SUCCESS = "LOGIN SUCCESS"
export const LOGIN_FAIL = "LOGIN FAIL"

export const REDIRECT = "REDIRECT"
export const CLEAR_MSG = "CLEAR_MSG"
